/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        gold: '#C5A059',
        'surface-bright': '#FAF9F6',
        background: '#FDFCFB',
        'on-primary-fixed-variant': '#004f50',
        'tertiary-fixed-dim': '#68dba9',
        'primary-fixed': '#aaefee',
        'on-primary': '#ffffff',
        'surface-container-low': '#f7f3ef',
        'surface-container': '#f4f1ed',
        'secondary-fixed': '#8cf2fd',
        outline: '#857370',
        'primary-container': '#0a5c5c',
        'records-primary-container': '#E3EDEC',
        'tertiary-fixed': '#85f8c4',
        surface: '#FAF9F6',
        'on-surface-variant': '#5a4d4d',
        'outline-variant': '#d8cfcc',
        'on-surface': '#2c2423',
        'surface-container-high': '#ebe6e1',
        'on-tertiary-fixed': '#002114',
        tertiary: '#00452e',
        'secondary-container': '#C8E6C9',
        primary: '#004343',
        'primary-fixed-dim': '#8ed2d2',
        'on-primary-container': '#002020',
        secondary: '#006971',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'section-gap': '120px',
        gutter: '24px',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        fraunces: ['Fraunces', 'serif'],
        'dm-serif': ['DM Serif Text', 'serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['40px', { lineHeight: '48px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
